language: java

script: travis_wait 120 ./.travis-build.sh

## Version for Ubuntu 14.04 Trusty.
## Problem: The job times out on travis-ci.org, but the container-based version
## does not.
# sudo: required
# dist: trusty
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq hevea librsvg2-bin texlive-fonts-recommended texlive-latex-base texlive-latex-extra

## Version for container-based infrastructure: Ubuntu 12.04.
## Problem:  Cannot build the manual because of problems generating fonts.
sudo: false
addons:
  apt:
    packages:
      # Reinstate jtreg when the build can use a standard jtreg install
      # - jtreg
      # for rsvg-convert
      - librsvg2-bin
      ## Save time by not installing LaTeX which is needed only for the manual
      # - hevea
      # # both for ecrm1000 (a font)
      # # This didn't help: - texlive-fonts-extra
      # - texlive-fonts-recommended
      # # for url.sty
      # - texlive-latex-base
      # # for fullpage.sty
      # - texlive-latex-extra

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - checker-framework-dev@googlegroups.com 

after_success:
  - curl -s https://raw.githubusercontent.com/mernst/plume-lib/master/bin/trigger-travis.sh > trigger-travis.sh  
  - bin/trigger-travis.sh codespecs checker-framework-demos $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs checker-framework-inference $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs daikon-typecheck $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs plume-lib-typecheck $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs sparta $TRAVISTOKEN
